[package]
name = "windows_features"
version = "0.1.0"
authors = ["Balthild <ibalthild@gmail.com>"]
edition = "2018"

[dependencies.native-dialog]
# version = "0.2.2"
path = "../.."
features = ["windows_dpi_awareness", "windows_visual_styles"]
